# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485004b7fa39fc50afa85265962ef0f2b22abdd11462c62c9e3dd5d6f0d2a3736a2df1a5b7d0947c98063a2be6257d12715065130e537ff1973da2c24fe2087b

test:
  secret_key_base: cc5fb9c2c867a50c61a86b68aa93b0dbe39b2740d7dcb70b37959e7d3c87f5f60bfa43bce5c130d88689a98c50e6aab6a421db7c76705b7025723767b4c09e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
